overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-ods3.yml
targets:
  - README.rst: custom_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - .travis.yml: custom_travis.yml.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - "tests/test_filter.py": "tests/test_filter.py.jj2"
  - "tests/test_formatters.py": "tests/test_formatters.py"
  - "tests/test_stringio.py": "tests/test_stringio.py.jj2"
  - "tests/test_writer.py": "tests/test_writer.py.jj2"
  - "tests/base.py": "tests/base.py.jj2"
