language: python
notifications:
  email: false
env:
  global:
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install git+https://github.com/T0ha/ezodf.git
  - pip install git+https://github.com/chfw/pyexcel-io.git
  - pip install git+https://github.com/chfw/pyexcel.git
  - pip install git+https://github.com/chfw/pyexcel-xls.git
  - pip install -r requirements.txt --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
script:
  make test
after_success:
  codecov
