sudo: false
language: python
notifications:
  email: false
python:
  - 2.7
  - 2.6
  - 3.3
  - 3.4
  - 3.5
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install ordereddict; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install weakrefset; fi
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov